name: peg
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - ca-certificates=2022.4.26=h06a4308_0
  - certifi=2021.5.30=py36h06a4308_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - cudnn=8.2.1=cuda11.3_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - ncurses=6.3=h7f8727e_2
  - openssl=1.1.1o=h7f8727e_0
  - pip=21.2.2=py36h06a4308_0
  - python=3.6.12=hcff3b4d_2
  - readline=8.1.2=h7f8727e_1
  - setuptools=58.0.4=py36h06a4308_0
  - sqlite=3.38.3=hc218d9a_0
  - tk=8.6.11=h1ccaba5_1
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7f8727e_1
  - zlib=1.2.12=h7f8727e_2
  - pip:
    - absl-py==0.12.0
    - anyio==3.6.1
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - astunparse==1.6.3
    - async-generator==1.10
    - atari-py==0.2.9
    - attrs==21.4.0
    - babel==2.10.3
    - backcall==0.2.0
    - bleach==4.1.0
    - cachetools==4.2.2
    - cffi==1.14.5
    - chardet==4.0.0
    - click==8.0.0
    - cloudpickle==1.6.0
    - contextvars==2.4
    - cycler==0.10.0
    - cython==0.29.23
    - dataclasses==0.8
    - decorator==5.0.7
    - defusedxml==0.7.1
    - dill==0.3.4
    - dm-env==1.4
    - dm-tree==0.1.6
    - entrypoints==0.4
    - fasteners==0.16
    - flatbuffers==1.12
    - future==0.18.2
    - gast==0.3.3
    - glfw==2.5.3
    - google-auth==1.30.0
    - google-auth-oauthlib==0.4.4
    - google-pasta==0.2.0
    - grpcio==1.32.0
    - gym==0.18.0
    - h5py==2.10.0
    - idna==2.10
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.7
    - immutables==0.18
    - importlib-metadata==4.0.1
    - ipdb==0.13.7
    - ipykernel==5.5.6
    - ipython==7.16.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.7.1
    - jedi==0.17.2
    - jinja2==3.0.3
    - joblib==1.1.0
    - json5==0.9.8
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==7.1.2
    - jupyter-console==6.4.3
    - jupyter-core==4.9.2
    - jupyter-server==1.13.1
    - jupyterlab==3.2.9
    - jupyterlab-pygments==0.1.2
    - jupyterlab-server==2.10.3
    - jupyterlab-widgets==1.1.1
    - keras-preprocessing==1.1.2
    - keyboard==0.13.5
    - kiwisolver==1.3.1
    - labmaze==1.0.4
    - llvmlite==0.36.0
    - lxml==4.6.3
    - markdown==3.3.4
    - markupsafe==2.0.1
    - matplotlib==3.3.4
    - mistune==0.8.4
    - mujoco-py==2.0.2.13
    - multiprocess==0.70.12.2
    - nbclassic==0.3.5
    - nbclient==0.5.9
    - nbconvert==6.0.7
    - nbformat==5.1.3
    - nest-asyncio==1.5.5
    - notebook==6.4.10
    - numba==0.53.1
    - numpy==1.19.5
    - numpy-quaternion==2021.4.5.14.42.35
    - oauthlib==3.1.0
    - opencv-python==4.5.2.52
    - opensimplex==0.3
    - opt-einsum==3.3.0
    - packaging==21.3
    - pandas==1.1.5
    - pandocfilters==1.5.0
    - parso==0.7.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==7.2.0
    - prometheus-client==0.14.1
    - prompt-toolkit==3.0.18
    - protobuf==3.16.0
    - ptyprocess==0.7.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.20
    - pygame==2.1.2
    - pyglet==1.5.0
    - pygments==2.9.0
    - pyopengl==3.1.5
    - pyparsing==2.4.7
    - pyquaternion==0.9.9
    - pyrsistent==0.18.0
    - python-dateutil==2.8.1
    - pytz==2022.1
    - pyzmq==23.2.0
    - qtconsole==5.2.2
    - qtpy==2.0.1
    - requests==2.25.1
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - ruamel-yaml==0.17.4
    - ruamel-yaml-clib==0.2.2
    - scikit-learn==0.24.2
    - scipy==1.5.4
    - seaborn==0.11.2
    - send2trash==1.8.0
    - six==1.15.0
    - sklearn==0.0
    - sniffio==1.2.0
    - tabulate==0.8.10
    - tensorboard==2.9.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow-estimator==2.4.0
    - tensorflow-gpu==2.4.1
    - tensorflow-probability==0.12.2
    - termcolor==1.1.0
    - terminado==0.12.1
    - testpath==0.6.0
    - threadpoolctl==3.1.0
    - toml==0.10.2
    - torch==1.10.2
    - tornado==6.1
    - tqdm==4.60.0
    - traitlets==4.3.3
    - typeguard==2.13.3
    - typing-extensions==3.7.4.3
    - urllib3==1.26.4
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.3.1
    - werkzeug==1.0.1
    - widgetsnbextension==3.6.1
    - wrapt==1.12.1
    - zipp==3.4.1
# variables:
#   D4RL_SUPPRESS_IMPORT_ERROR: '1'
#   MUJOCO_GL: egl
#   MUJOCO_RENDERER: egl
#   # PYTHONPATH: /home/edward/projects/mrl
# prefix: /home/edward/miniconda3/envs/peg
